//! Bakes the built interface into the binary.
//!
//! The promise on the install page is one command and then a working
//! product. A daemon that serves an API and tells the owner to install
//! Node.js and run a dev server has not kept it.
//!
//! So `knowlith/dist` — whatever `npm run build` produced — is turned into
//! a static table of `(path, bytes)` and compiled in. One file ships, and
//! `knowlith serve` opens a real interface on a machine that has never seen
//! a package manager.
//!
//! When the interface has not been built, the table is empty and the server
//! says so in a sentence. That is deliberate: a developer working on the
//! Rust side should not have to build the front end first, and the failure
//! should be a legible message rather than a missing file.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest
        .parent()
        .and_then(|p| p.parent())
        .map(|root| root.join("knowlith").join("dist"))
        .unwrap_or_default();

    // Rebuilt when the interface is rebuilt, and not on every `cargo build`.
    println!("cargo:rerun-if-changed={}", dist.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut files = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut files);
        files.sort();
    }

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs. Do not edit.\n");
    let _ = writeln!(
        generated,
        "pub static ASSETS: &[(&str, &[u8])] = &[",
    );
    for (route, path) in &files {
        // `include_bytes!` takes a literal, so the absolute path is written
        // in. That is fine: this file is regenerated on every machine that
        // compiles, and never committed.
        let _ = writeln!(
            generated,
            "    ({route:?}, include_bytes!({:?})),",
            path.to_string_lossy()
        );
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("assets.rs");
    std::fs::write(&out, generated).expect("could not write the asset table");
}

/// Every file under `dist`, as the path a browser would ask for.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // Always forward slashes: this is a URL, not a path, and a Windows
        // build would otherwise serve routes nobody can request.
        let route = relative
            .components()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/");
        out.push((route, path));
    }
}
